### ISSUE TITLE
create vm

### ISSUE THREAD

**Issue by spuder** [cjohannsen81/knife-acropolis#2]
Just switching to nutanix, and we are excited to start using this plugin. 

Looks like create vm isn't implemented yet. I'd like to help where I can in getting that feature released.

**Comment by spuder** [comment]
I've got a basic implementation working with hard coded values to create a VM. 

I don't want to be duplicating any work that you may already have written. @cjohannsen81 have you started work on create vm?

**Comment by spuder** [comment]
I've got 2 pull requests incoming

@cjohannsen81 I see on your blog you no longer work for nutanix

Will this project continue to be maintained? If not, are you looking for maintainers?

**Comment by cjohannsen81** [comment]
@spuder Hi Spencer, thanks for adding all the functions. Please excuse the delay. I would love to add you as a maintainer.

**Comment by cjohannsen81** [comment]
Added as collaborator.
